

- name: "print debug message"
  debug:
    msg: "linking file: {{ item.name }}"

- name: ensure proper config directory
  block:
    # register the directory
    - name: directory exists
      stat:
        path: "{{ home_directory }}/{{ item.dest }}"
      register: dotfile_directory_stat

    # directory exists   
    - name: echo if base config exists
      debug:
        msg: base config directory [{{ dotfile_directory_stat.stat.path }}] exists
      when: dotfile_directory_stat.stat.exists  

    # directory doesnt exist  
    - name: echo if base config directory doesnt exist
      debug:
        msg: base config directory [{{ dotfile_directory_stat.stat.path }}] doesnt exist
      when: not dotfile_directory_stat.stat.exists   

    # create dir since it doesnt exist
    - name: creating directory...
      file:
        path: "{{ dotfile_directory_stat.path }}"
        state: directory
        mode: 0755
      when: not dotfile_directory_stat.stat.exists

  when: item.dest is defined

# link the file
- name: soft linking config file...
  file:
    state: link
    src: "{{ working_directory }}/dotfiles/{{ item.file_name }}"
    dest: "{{ home_directory }}/{{ item.dest + '/' | default('') }}{{ item.file_name }}"
    mode: 0755
    force: yes