---
# tasks file for scottweitzner.dotfile-sync

# TODO: potentially fail if dir exists
- name: initialize the git repo
  git:
    repo: "{{ dotfiles_git_repo }}"
    dest: "{{ working_directory }}/dotfiles"
    clone: yes
    recursive: yes
  tags: 
    - never
    - init

- name: link dotfiles
  include_tasks: 
    file: link.yml
    apply:
        tags:
          - always
  with_items: "{{ files_to_sync }}"
  tags:
    - never
    - link