---
# tasks file for scottweitzner.dotfile-sync

# TODO: potentially fail if dir exists
- name: initialize the git repo
  git:
    repo: git@gitlab.com:sweitzne/dotfiles.git
    dest: "{{ working_directory }}/dotfiles"
    clone: yes
    recursive: yes
  tags: 
    - never
    - init

- name: link alacritty
  include: link.yml
  vars:
    dotfile_directory: "{{ home_directory }}/.config/alacritty"
    file_name: alacritty.yml
  tags:
    - never
    - link

- name: link ohmyzsh theme
  include: link.yml
  vars:
    dotfile_directory: "{{ home_directory }}/.oh-my-zsh/themes"
    file_name: sweitzne.zsh-theme
  tags:
    - never
    - link

